"use client";

import { useActionState, useEffect, useRef } from "react";
import type { OpportunityFormState } from "@/lib/data-access/opportunities";

const initialState: OpportunityFormState = {};
type OpportunityAction = (state: OpportunityFormState, formData: FormData) => Promise<OpportunityFormState>;

export function OpportunityForm({ action, customers }: Readonly<{ action: OpportunityAction; customers: Array<{ id: string; company_name: string }> }>) {
  const [state, formAction, isPending] = useActionState(action, initialState);
  const formRef = useRef<HTMLFormElement>(null);
  useEffect(() => { if (state.success) formRef.current?.reset(); }, [state.success]);
  return <form action={formAction} className="space-y-5" ref={formRef}><div className="grid gap-5 sm:grid-cols-2"><label className="text-sm font-medium sm:col-span-2">Kunde<select className="mt-2 h-11 w-full border border-[#c8d5cf] bg-white px-3 font-normal outline-none focus:border-[#c45c3d]" name="customerId" required><option value="">Velg kunde</option>{customers.map((customer) => <option key={customer.id} value={customer.id}>{customer.company_name}</option>)}</select>{state.fieldErrors?.customerId ? <span className="mt-1 block text-xs text-[#a63e2a]">{state.fieldErrors.customerId[0]}</span> : null}</label><label className="text-sm font-medium sm:col-span-2">Tittel<input className="mt-2 h-11 w-full border border-[#c8d5cf] bg-white px-3 font-normal outline-none focus:border-[#c45c3d]" name="title" required />{state.fieldErrors?.title ? <span className="mt-1 block text-xs text-[#a63e2a]">{state.fieldErrors.title[0]}</span> : null}</label><label className="text-sm font-medium">Verdi (NOK)<input className="mt-2 h-11 w-full border border-[#c8d5cf] bg-white px-3 font-normal outline-none focus:border-[#c45c3d]" defaultValue="0" min="0" name="value" step="1000" type="number" /></label><label className="text-sm font-medium">Sannsynlighet (%)<input className="mt-2 h-11 w-full border border-[#c8d5cf] bg-white px-3 font-normal outline-none focus:border-[#c45c3d]" defaultValue="10" max="100" min="0" name="probability" type="number" /></label><label className="text-sm font-medium">Forventet avslutning<input className="mt-2 h-11 w-full border border-[#c8d5cf] bg-white px-3 font-normal outline-none focus:border-[#c45c3d]" name="expectedCloseDate" type="date" /></label></div><label className="block text-sm font-medium">Beskrivelse<textarea className="mt-2 min-h-24 w-full border border-[#c8d5cf] bg-white px-3 py-2 font-normal outline-none focus:border-[#c45c3d]" name="description" /></label>{state.error ? <p className="text-sm text-[#a63e2a]" role="alert">{state.error}</p> : null}{state.success ? <p className="text-sm text-[#31554a]" role="status">Muligheten er opprettet.</p> : null}<button className="h-11 bg-[#19332d] px-5 text-sm font-semibold text-white disabled:opacity-60" disabled={isPending} type="submit">{isPending ? "Oppretter..." : "Opprett mulighet"}</button></form>;
}
