"use client";

import { useActionState, useEffect, useRef } from "react";
import type { ActivityFormState, ActivityParentOption } from "@/lib/data-access/activities";

const initialState: ActivityFormState = {};
type ActivityAction = (state: ActivityFormState, formData: FormData) => Promise<ActivityFormState>;

export function ActivityForm({ action, customers, opportunities }: Readonly<{ action: ActivityAction; customers: ActivityParentOption[]; opportunities: ActivityParentOption[] }>) {
  const [state, formAction, isPending] = useActionState(action, initialState);
  const formRef = useRef<HTMLFormElement>(null);
  useEffect(() => { if (state.success) formRef.current?.reset(); }, [state.success]);
  return <form action={formAction} className="space-y-5" ref={formRef}><div className="grid gap-5 sm:grid-cols-2"><label className="text-sm font-medium sm:col-span-2">Tittel<input className="mt-2 h-11 w-full border border-[#c8d5cf] px-3 font-normal outline-none focus:border-[#c45c3d]" name="title" required />{state.fieldErrors?.title ? <span className="mt-1 block text-xs text-[#a63e2a]">{state.fieldErrors.title[0]}</span> : null}</label><label className="text-sm font-medium">Type<select className="mt-2 h-11 w-full border border-[#c8d5cf] px-3 font-normal outline-none focus:border-[#c45c3d]" defaultValue="follow_up" name="type"><option value="call">Samtale</option><option value="email">E-post</option><option value="meeting">Møte</option><option value="follow_up">Oppfølging</option><option value="task">Oppgave</option><option value="note">Notat</option></select></label><label className="text-sm font-medium">Prioritet<select className="mt-2 h-11 w-full border border-[#c8d5cf] px-3 font-normal outline-none focus:border-[#c45c3d]" defaultValue="normal" name="priority"><option value="low">Lav</option><option value="normal">Normal</option><option value="high">Høy</option></select></label><label className="text-sm font-medium">Forfallsdato<input className="mt-2 h-11 w-full border border-[#c8d5cf] px-3 font-normal outline-none focus:border-[#c45c3d]" name="dueDate" type="datetime-local" /></label><label className="text-sm font-medium">Kunde<select className="mt-2 h-11 w-full border border-[#c8d5cf] px-3 font-normal outline-none focus:border-[#c45c3d]" defaultValue="" name="customerId"><option value="">Ingen kunde valgt</option>{customers.map((customer) => <option key={customer.id} value={customer.id}>{customer.label}</option>)}</select></label><label className="text-sm font-medium">Mulighet<select className="mt-2 h-11 w-full border border-[#c8d5cf] px-3 font-normal outline-none focus:border-[#c45c3d]" defaultValue="" name="opportunityId"><option value="">Ingen mulighet valgt</option>{opportunities.map((opportunity) => <option key={opportunity.id} value={opportunity.id}>{opportunity.label}</option>)}</select></label></div><label className="block text-sm font-medium">Beskrivelse<textarea className="mt-2 min-h-24 w-full border border-[#c8d5cf] px-3 py-2 font-normal outline-none focus:border-[#c45c3d]" name="description" /></label>{state.error ? <p className="text-sm text-[#a63e2a]" role="alert">{state.error}</p> : null}{state.fieldErrors?.customerId ? <p className="text-sm text-[#a63e2a]">{state.fieldErrors.customerId[0]}</p> : null}{state.success ? <p className="text-sm text-[#31554a]" role="status">Aktiviteten er opprettet.</p> : null}<button className="h-11 bg-[#19332d] px-5 text-sm font-semibold text-white disabled:opacity-60" disabled={isPending} type="submit">{isPending ? "Oppretter..." : "Opprett aktivitet"}</button></form>;
}
